### ISSUE TITLE
Empty Chapters & Non Related Chapters to React Native

### ISSUE THREAD

**Issue by kadrianus** [checkraiser/beginning-react-native#1]
Empty Chapters:

2.1 - Flux in React Native 
3 - Adding basic components
4 - Adding Flexbox layout
6 - Working with JSON
10 -Testing React-Native components

Mostly Objective-C Code  (No ReactNative information)

1 - Installation and setup new project (pure Objective C chapter)
5 - Building Node.js Server for API (pure Node.js, Express framework chapter)
8 - Custom SQLite Module (pure Objective C chapter)
9 - Integration with AdmobSDK (pure Objective C chapter)

So, from a 10 chapters book related to ReactNative, 4 are empty, 4 speaks about another technology and the resting 2 chapters they uses coded not updated to the actual version of React Native.

**Comment by revskill10** [comment]
Hi, in the introduction, you don't need to be Objective-C master to develop React Native code, but to integrate external libraries into your code, i will guide you so that you understand how to extend your codebase to adapt your need. I think you misunderstand the problem here.
Anyway, i'm updating my code to get the project as universal as possible for you to implement in your own project.
Stay tune.
